//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuStore.WebUI.CrmService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerData", Namespace="http://schemas.datacontract.org/2004/07/CuStore.CRMService.OperationContracts")]
    [System.SerializableAttribute()]
    public partial class CustomerData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RatioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalCode {
            get {
                return this.ExternalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalCodeField, value) != true)) {
                    this.ExternalCodeField = value;
                    this.RaisePropertyChanged("ExternalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ratio {
            get {
                return this.RatioField;
            }
            set {
                if ((this.RatioField.Equals(value) != true)) {
                    this.RatioField = value;
                    this.RaisePropertyChanged("Ratio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrmService.ICrmService")]
    public interface ICrmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetCustomerData", ReplyAction="http://tempuri.org/ICrmService/GetCustomerDataResponse")]
        CuStore.WebUI.CrmService.CustomerData GetCustomerData(System.Guid customerId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICrmService/GetCustomerData", ReplyAction="http://tempuri.org/ICrmService/GetCustomerDataResponse")]
        System.IAsyncResult BeginGetCustomerData(System.Guid customerId, System.AsyncCallback callback, object asyncState);
        
        CuStore.WebUI.CrmService.CustomerData EndGetCustomerData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/GetPoints", ReplyAction="http://tempuri.org/ICrmService/GetPointsResponse")]
        int GetPoints(System.Guid customerId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICrmService/GetPoints", ReplyAction="http://tempuri.org/ICrmService/GetPointsResponse")]
        System.IAsyncResult BeginGetPoints(System.Guid customerId, System.AsyncCallback callback, object asyncState);
        
        int EndGetPoints(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/AddCustomer", ReplyAction="http://tempuri.org/ICrmService/AddCustomerResponse")]
        System.Guid AddCustomer(string externalCode, int bonusPoints);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICrmService/AddCustomer", ReplyAction="http://tempuri.org/ICrmService/AddCustomerResponse")]
        System.IAsyncResult BeginAddCustomer(string externalCode, int bonusPoints, System.AsyncCallback callback, object asyncState);
        
        System.Guid EndAddCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/AddCustomerData", ReplyAction="http://tempuri.org/ICrmService/AddCustomerDataResponse")]
        bool AddCustomerData(CuStore.WebUI.CrmService.CustomerData customerData);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICrmService/AddCustomerData", ReplyAction="http://tempuri.org/ICrmService/AddCustomerDataResponse")]
        System.IAsyncResult BeginAddCustomerData(CuStore.WebUI.CrmService.CustomerData customerData, System.AsyncCallback callback, object asyncState);
        
        bool EndAddCustomerData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/RemoveCustomer", ReplyAction="http://tempuri.org/ICrmService/RemoveCustomerResponse")]
        bool RemoveCustomer(System.Guid customerId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICrmService/RemoveCustomer", ReplyAction="http://tempuri.org/ICrmService/RemoveCustomerResponse")]
        System.IAsyncResult BeginRemoveCustomer(System.Guid customerId, System.AsyncCallback callback, object asyncState);
        
        bool EndRemoveCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmService/AddPointForCustomer", ReplyAction="http://tempuri.org/ICrmService/AddPointForCustomerResponse")]
        bool AddPointForCustomer(System.Guid customerId, int points);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICrmService/AddPointForCustomer", ReplyAction="http://tempuri.org/ICrmService/AddPointForCustomerResponse")]
        System.IAsyncResult BeginAddPointForCustomer(System.Guid customerId, int points, System.AsyncCallback callback, object asyncState);
        
        bool EndAddPointForCustomer(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrmServiceChannel : CuStore.WebUI.CrmService.ICrmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomerDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCustomerDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CuStore.WebUI.CrmService.CustomerData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CuStore.WebUI.CrmService.CustomerData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPointsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPointsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Guid Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddCustomerDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddCustomerDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoveCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RemoveCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddPointForCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddPointForCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrmServiceClient : System.ServiceModel.ClientBase<CuStore.WebUI.CrmService.ICrmService>, CuStore.WebUI.CrmService.ICrmService {
        
        private BeginOperationDelegate onBeginGetCustomerDataDelegate;
        
        private EndOperationDelegate onEndGetCustomerDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetCustomerDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPointsDelegate;
        
        private EndOperationDelegate onEndGetPointsDelegate;
        
        private System.Threading.SendOrPostCallback onGetPointsCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddCustomerDelegate;
        
        private EndOperationDelegate onEndAddCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onAddCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddCustomerDataDelegate;
        
        private EndOperationDelegate onEndAddCustomerDataDelegate;
        
        private System.Threading.SendOrPostCallback onAddCustomerDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveCustomerDelegate;
        
        private EndOperationDelegate onEndRemoveCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddPointForCustomerDelegate;
        
        private EndOperationDelegate onEndAddPointForCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onAddPointForCustomerCompletedDelegate;
        
        public CrmServiceClient() {
        }
        
        public CrmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetCustomerDataCompletedEventArgs> GetCustomerDataCompleted;
        
        public event System.EventHandler<GetPointsCompletedEventArgs> GetPointsCompleted;
        
        public event System.EventHandler<AddCustomerCompletedEventArgs> AddCustomerCompleted;
        
        public event System.EventHandler<AddCustomerDataCompletedEventArgs> AddCustomerDataCompleted;
        
        public event System.EventHandler<RemoveCustomerCompletedEventArgs> RemoveCustomerCompleted;
        
        public event System.EventHandler<AddPointForCustomerCompletedEventArgs> AddPointForCustomerCompleted;
        
        public CuStore.WebUI.CrmService.CustomerData GetCustomerData(System.Guid customerId) {
            return base.Channel.GetCustomerData(customerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCustomerData(System.Guid customerId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomerData(customerId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public CuStore.WebUI.CrmService.CustomerData EndGetCustomerData(System.IAsyncResult result) {
            return base.Channel.EndGetCustomerData(result);
        }
        
        private System.IAsyncResult OnBeginGetCustomerData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid customerId = ((System.Guid)(inValues[0]));
            return this.BeginGetCustomerData(customerId, callback, asyncState);
        }
        
        private object[] OnEndGetCustomerData(System.IAsyncResult result) {
            CuStore.WebUI.CrmService.CustomerData retVal = this.EndGetCustomerData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCustomerDataCompleted(object state) {
            if ((this.GetCustomerDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomerDataCompleted(this, new GetCustomerDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCustomerDataAsync(System.Guid customerId) {
            this.GetCustomerDataAsync(customerId, null);
        }
        
        public void GetCustomerDataAsync(System.Guid customerId, object userState) {
            if ((this.onBeginGetCustomerDataDelegate == null)) {
                this.onBeginGetCustomerDataDelegate = new BeginOperationDelegate(this.OnBeginGetCustomerData);
            }
            if ((this.onEndGetCustomerDataDelegate == null)) {
                this.onEndGetCustomerDataDelegate = new EndOperationDelegate(this.OnEndGetCustomerData);
            }
            if ((this.onGetCustomerDataCompletedDelegate == null)) {
                this.onGetCustomerDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomerDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomerDataDelegate, new object[] {
                        customerId}, this.onEndGetCustomerDataDelegate, this.onGetCustomerDataCompletedDelegate, userState);
        }
        
        public int GetPoints(System.Guid customerId) {
            return base.Channel.GetPoints(customerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetPoints(System.Guid customerId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPoints(customerId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndGetPoints(System.IAsyncResult result) {
            return base.Channel.EndGetPoints(result);
        }
        
        private System.IAsyncResult OnBeginGetPoints(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid customerId = ((System.Guid)(inValues[0]));
            return this.BeginGetPoints(customerId, callback, asyncState);
        }
        
        private object[] OnEndGetPoints(System.IAsyncResult result) {
            int retVal = this.EndGetPoints(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPointsCompleted(object state) {
            if ((this.GetPointsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPointsCompleted(this, new GetPointsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPointsAsync(System.Guid customerId) {
            this.GetPointsAsync(customerId, null);
        }
        
        public void GetPointsAsync(System.Guid customerId, object userState) {
            if ((this.onBeginGetPointsDelegate == null)) {
                this.onBeginGetPointsDelegate = new BeginOperationDelegate(this.OnBeginGetPoints);
            }
            if ((this.onEndGetPointsDelegate == null)) {
                this.onEndGetPointsDelegate = new EndOperationDelegate(this.OnEndGetPoints);
            }
            if ((this.onGetPointsCompletedDelegate == null)) {
                this.onGetPointsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPointsCompleted);
            }
            base.InvokeAsync(this.onBeginGetPointsDelegate, new object[] {
                        customerId}, this.onEndGetPointsDelegate, this.onGetPointsCompletedDelegate, userState);
        }
        
        public System.Guid AddCustomer(string externalCode, int bonusPoints) {
            return base.Channel.AddCustomer(externalCode, bonusPoints);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddCustomer(string externalCode, int bonusPoints, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddCustomer(externalCode, bonusPoints, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Guid EndAddCustomer(System.IAsyncResult result) {
            return base.Channel.EndAddCustomer(result);
        }
        
        private System.IAsyncResult OnBeginAddCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string externalCode = ((string)(inValues[0]));
            int bonusPoints = ((int)(inValues[1]));
            return this.BeginAddCustomer(externalCode, bonusPoints, callback, asyncState);
        }
        
        private object[] OnEndAddCustomer(System.IAsyncResult result) {
            System.Guid retVal = this.EndAddCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddCustomerCompleted(object state) {
            if ((this.AddCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCustomerCompleted(this, new AddCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddCustomerAsync(string externalCode, int bonusPoints) {
            this.AddCustomerAsync(externalCode, bonusPoints, null);
        }
        
        public void AddCustomerAsync(string externalCode, int bonusPoints, object userState) {
            if ((this.onBeginAddCustomerDelegate == null)) {
                this.onBeginAddCustomerDelegate = new BeginOperationDelegate(this.OnBeginAddCustomer);
            }
            if ((this.onEndAddCustomerDelegate == null)) {
                this.onEndAddCustomerDelegate = new EndOperationDelegate(this.OnEndAddCustomer);
            }
            if ((this.onAddCustomerCompletedDelegate == null)) {
                this.onAddCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginAddCustomerDelegate, new object[] {
                        externalCode,
                        bonusPoints}, this.onEndAddCustomerDelegate, this.onAddCustomerCompletedDelegate, userState);
        }
        
        public bool AddCustomerData(CuStore.WebUI.CrmService.CustomerData customerData) {
            return base.Channel.AddCustomerData(customerData);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddCustomerData(CuStore.WebUI.CrmService.CustomerData customerData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddCustomerData(customerData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndAddCustomerData(System.IAsyncResult result) {
            return base.Channel.EndAddCustomerData(result);
        }
        
        private System.IAsyncResult OnBeginAddCustomerData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CuStore.WebUI.CrmService.CustomerData customerData = ((CuStore.WebUI.CrmService.CustomerData)(inValues[0]));
            return this.BeginAddCustomerData(customerData, callback, asyncState);
        }
        
        private object[] OnEndAddCustomerData(System.IAsyncResult result) {
            bool retVal = this.EndAddCustomerData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddCustomerDataCompleted(object state) {
            if ((this.AddCustomerDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCustomerDataCompleted(this, new AddCustomerDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddCustomerDataAsync(CuStore.WebUI.CrmService.CustomerData customerData) {
            this.AddCustomerDataAsync(customerData, null);
        }
        
        public void AddCustomerDataAsync(CuStore.WebUI.CrmService.CustomerData customerData, object userState) {
            if ((this.onBeginAddCustomerDataDelegate == null)) {
                this.onBeginAddCustomerDataDelegate = new BeginOperationDelegate(this.OnBeginAddCustomerData);
            }
            if ((this.onEndAddCustomerDataDelegate == null)) {
                this.onEndAddCustomerDataDelegate = new EndOperationDelegate(this.OnEndAddCustomerData);
            }
            if ((this.onAddCustomerDataCompletedDelegate == null)) {
                this.onAddCustomerDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCustomerDataCompleted);
            }
            base.InvokeAsync(this.onBeginAddCustomerDataDelegate, new object[] {
                        customerData}, this.onEndAddCustomerDataDelegate, this.onAddCustomerDataCompletedDelegate, userState);
        }
        
        public bool RemoveCustomer(System.Guid customerId) {
            return base.Channel.RemoveCustomer(customerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginRemoveCustomer(System.Guid customerId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemoveCustomer(customerId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndRemoveCustomer(System.IAsyncResult result) {
            return base.Channel.EndRemoveCustomer(result);
        }
        
        private System.IAsyncResult OnBeginRemoveCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid customerId = ((System.Guid)(inValues[0]));
            return this.BeginRemoveCustomer(customerId, callback, asyncState);
        }
        
        private object[] OnEndRemoveCustomer(System.IAsyncResult result) {
            bool retVal = this.EndRemoveCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRemoveCustomerCompleted(object state) {
            if ((this.RemoveCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveCustomerCompleted(this, new RemoveCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveCustomerAsync(System.Guid customerId) {
            this.RemoveCustomerAsync(customerId, null);
        }
        
        public void RemoveCustomerAsync(System.Guid customerId, object userState) {
            if ((this.onBeginRemoveCustomerDelegate == null)) {
                this.onBeginRemoveCustomerDelegate = new BeginOperationDelegate(this.OnBeginRemoveCustomer);
            }
            if ((this.onEndRemoveCustomerDelegate == null)) {
                this.onEndRemoveCustomerDelegate = new EndOperationDelegate(this.OnEndRemoveCustomer);
            }
            if ((this.onRemoveCustomerCompletedDelegate == null)) {
                this.onRemoveCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveCustomerDelegate, new object[] {
                        customerId}, this.onEndRemoveCustomerDelegate, this.onRemoveCustomerCompletedDelegate, userState);
        }
        
        public bool AddPointForCustomer(System.Guid customerId, int points) {
            return base.Channel.AddPointForCustomer(customerId, points);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddPointForCustomer(System.Guid customerId, int points, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddPointForCustomer(customerId, points, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndAddPointForCustomer(System.IAsyncResult result) {
            return base.Channel.EndAddPointForCustomer(result);
        }
        
        private System.IAsyncResult OnBeginAddPointForCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid customerId = ((System.Guid)(inValues[0]));
            int points = ((int)(inValues[1]));
            return this.BeginAddPointForCustomer(customerId, points, callback, asyncState);
        }
        
        private object[] OnEndAddPointForCustomer(System.IAsyncResult result) {
            bool retVal = this.EndAddPointForCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddPointForCustomerCompleted(object state) {
            if ((this.AddPointForCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddPointForCustomerCompleted(this, new AddPointForCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddPointForCustomerAsync(System.Guid customerId, int points) {
            this.AddPointForCustomerAsync(customerId, points, null);
        }
        
        public void AddPointForCustomerAsync(System.Guid customerId, int points, object userState) {
            if ((this.onBeginAddPointForCustomerDelegate == null)) {
                this.onBeginAddPointForCustomerDelegate = new BeginOperationDelegate(this.OnBeginAddPointForCustomer);
            }
            if ((this.onEndAddPointForCustomerDelegate == null)) {
                this.onEndAddPointForCustomerDelegate = new EndOperationDelegate(this.OnEndAddPointForCustomer);
            }
            if ((this.onAddPointForCustomerCompletedDelegate == null)) {
                this.onAddPointForCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddPointForCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginAddPointForCustomerDelegate, new object[] {
                        customerId,
                        points}, this.onEndAddPointForCustomerDelegate, this.onAddPointForCustomerCompletedDelegate, userState);
        }
    }
}
